modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="pokey_and_alexs__mc_mod"
version="3.15.19"
displayName="pokey and alex's mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Pokey_yt , Alex super 199"
description='''
a neat little collab mod
'''

[[dependencies.pokey_and_alexs__mc_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.pokey_and_alexs__mc_mod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

